Repository afterpay/sdk-ios, pull requests merged in 2020-08, with the labels that each got.

#96 Cache Afterpay configuration in example app
  Example/Example.xcodeproj/project.pbxproj
  Example/Example/AppFlowController.swift
  Example/Example/Shared/APIClient.swift
  Example/Example/Shared/Dependencies.swift
  Example/Example/Shared/Networking.swift
  Example/Example/Shared/Repository.swift
  Example/Example/SwiftUI/Environment.swift
  Example/Example/SwiftUI/SwiftUIExample.swift
Labels: enhancement

#100 Add InfoWebViewController for viewing Afterpay information links
  Afterpay.podspec
  Afterpay.xcodeproj/project.pbxproj
  Sources/Afterpay/Afterpay.swift
  Sources/Afterpay/Checkout/CheckoutResult.swift
  Sources/Afterpay/Checkout/CheckoutWebViewController.swift
  Sources/Afterpay/Info/InfoWebViewController.swift
  Sources/Afterpay/Wrappers/SwiftUIWrapper.swift
Labels: enhancement

#102 Allow the option to implement a delegate and launch the info modal
  Example/Example/Components/ComponentsViewController.swift
  Sources/Afterpay/Info/InfoWebViewController.swift
  Sources/Afterpay/Views/PriceBreakdownView.swift
Labels: enhancement

#103 Price Breakdown Logic
  Afterpay.xcodeproj/project.pbxproj
  Example/Example/Components/ComponentsViewController.swift
  Sources/Afterpay/Afterpay.swift
  Sources/Afterpay/Model/Configuration.swift
  Sources/Afterpay/Model/Currency.swift
  Sources/Afterpay/Model/PriceBreakdown.swift
  Sources/Afterpay/Views/PriceBreakdownView.swift
Labels: enhancement

#106 Fix scroll view height ambiguity by adding containment views
  Example/Example/Components/ComponentsViewController.swift
Labels: bug

#105 Add the ability to view the purchase-payment-agreement in browser
  Sources/Afterpay/Info/InfoWebViewController.swift
Labels: enhancement

#104 Add unit tests for PriceBreakdown
  Afterpay.xcodeproj/project.pbxproj
  AfterpayTests/PriceBreakdownTests.swift
  Sources/Afterpay/Afterpay.swift
  Sources/Afterpay/Model/PriceBreakdown.swift
Labels: chore

#114 Prepare iOS for a 1.2.0 release adding documentation and ensuring features are accessible
  Configurations/Afterpay-Shared.xcconfig
  Images/badge_black_on_mint.png
  Images/badge_black_on_white.png
  Images/badge_mint_on_black.png
  Images/badge_white_on_black.png
  Images/four-payments.png
  README.md
  Sources/Afterpay/Views/BadgeView.swift
  Sources/Afterpay/Views/PriceBreakdownView.swift
  Sources/Afterpay/Views/SVGView.swift
Labels: documentation
