Repository afterpay/sdk-ios, pull requests merged in 2020-07, with the labels that each got.

#80 Harden Swiftlint build phase script to avoid build failures
  Afterpay.xcodeproj/project.pbxproj
  Scripts/swiftlint-sdk
Labels: bug

#81 Update the README with version 1.0.1 relevant content
  README.md
Labels: documentation

#83 Add the zip argument to generate the xcframework in a zipped format
  Scripts/create-xcframework
Labels: chore

#84 Add Cocoapods support and release deployment
  .github/workflows/deploy_to_cocoapods.yml
  Afterpay.podspec
Labels: enhancement

#85 Prepare CocoaPods release version (1.0.2)
  .github/workflows/deploy_to_cocoapods.yml
  Configurations/Afterpay-Shared.xcconfig
  README.md
Labels: chore

#86 Update CocoaPods deployment to run on published releases
  .github/workflows/deploy_to_cocoapods.yml
Labels: bug

#87 Update integration docs
  README.md
Labels: documentation

#88 Add an authentication challenge handler to the SDK
  Afterpay.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Configurations/Afterpay-Shared.xcconfig
  Example/Example.xcodeproj/project.pbxproj
  Example/Example/AppDelegate.swift
  Example/Example/AppFlowController.swift
  Example/Example/Shared/Dependencies.swift
  README.md
  Sources/Afterpay/Afterpay.swift
  Sources/Afterpay/ObjcWrapper.swift
  Sources/Afterpay/WebViewController.swift
Labels: enhancement

#89 Add settable Configuration object to the SDK
  Afterpay.xcodeproj/project.pbxproj
  AfterpayTests/AfterpayTests.swift
  AfterpayTests/ConfigurationTests.swift
  Sources/Afterpay/Afterpay.swift
  Sources/Afterpay/Configuration.swift
  Sources/Afterpay/ObjcWrapper.swift
Labels: enhancement

#90 Add GitHub action to validate Afterpay SDK pod
  .github/workflows/build-and-test.yml
Labels: enhancement

#92 Set the merchant configuration in the example app
  Example/Example/AppFlowController.swift
  Example/Example/Shared/AlertFactory.swift
  Example/Example/Shared/Dependencies.swift
  Example/Example/Shared/Networking.swift
  Example/Example/SwiftUI/SwiftUIExample.swift
Labels: enhancement
